from facefusion import config
import facefusion.choices

attribute_config_mapping = {
    'source_paths': (config.get_str_list, 'general.source_paths', None),
    'target_path': (config.get_str_value, 'general.target_path', None),
    'output_path': (config.get_str_value, 'general.output_path', None),
    'force_download': (config.get_bool_value, 'misc.force_download', None),
    'skip_download': (config.get_bool_value, 'misc.skip_download', None),
    'headless': (config.get_bool_value, 'misc.headless', None),
    'log_level': (config.get_str_value, 'misc.log_level', 'info'),
    'execution_providers': (config.get_str_list, 'execution.execution_providers', 'cpu'),
    'execution_thread_count': (config.get_int_value, 'execution.execution_thread_count', '4'),
    'execution_queue_count': (config.get_int_value, 'execution.execution_queue_count', '1'),
    'video_memory_strategy': (config.get_str_value, 'memory.video_memory_strategy', 'strict'),
    'system_memory_limit': (config.get_int_value, 'memory.system_memory_limit', '0'),
    'face_analyser_order': (config.get_str_value, 'face_analyser.face_analyser_order', 'left-right'),
    'face_analyser_age': (config.get_str_value, 'face_analyser.face_analyser_age', None),
    'face_analyser_gender': (config.get_str_value, 'face_analyser.face_analyser_gender', None),
    'face_detector_model': (config.get_str_value, 'face_analyser.face_detector_model', 'yoloface'),
    'face_detector_size': (config.get_str_value, 'face_analyser.face_detector_size', '640x640'),
    'face_detector_score': (config.get_float_value, 'face_analyser.face_detector_score', '0.5'),
    'face_landmarker_score': (config.get_float_value, 'face_analyser.face_landmarker_score', '0.5'),
    'face_selector_mode': (config.get_str_value, 'face_selector.face_selector_mode', 'reference'),
    'reference_face_position': (config.get_int_value, 'face_selector.reference_face_position', '0'),    
    'reference_face_distance': (config.get_float_value, 'face_selector.reference_face_distance', '0.6'),
    'reference_frame_number': (config.get_int_value, 'face_selector.reference_frame_number', '0'),
    'face_mask_types': (config.get_str_list, 'face_mask.face_mask_types', 'box'),
    'face_mask_blur': (config.get_float_value, 'face_mask.face_mask_blur', '0.3'),
    'face_mask_padding': (config.get_int_list, 'face_mask.face_mask_padding', '0 0 0 0'),
    'face_mask_regions': (config.get_str_list, 'face_mask.face_mask_regions', ' '.join(facefusion.choices.face_mask_regions)),
    'trim_frame_start': (config.get_int_value, 'frame_extraction.trim_frame_start', None),
    'trim_frame_end': (config.get_int_value, 'frame_extraction.trim_frame_end', None),
    'temp_frame_format': (config.get_str_value, 'frame_extraction.temp_frame_format', 'png'),
    'keep_temp': (config.get_bool_value, 'frame_extraction.keep_temp', None),
    'output_image_quality': (config.get_int_value, 'output_creation.output_image_quality', '80'),
    'output_image_resolution': (config.get_str_value, 'output_creation.output_image_resolution', None),
    'output_video_encoder': (config.get_str_value, 'output_creation.output_video_encoder', 'libx264'),
    'output_video_preset': (config.get_str_value, 'output_creation.output_video_preset', 'veryfast'),
    'output_video_quality': (config.get_int_value, 'output_creation.output_video_quality', '80'),
    'output_video_resolution': (config.get_str_value, 'output_creation.output_video_resolution', None),
    'output_video_fps': (config.get_float_value, 'output_creation.output_video_fps', None),
    'skip_audio': (config.get_bool_value, 'output_creation.skip_audio', None),
	'frame_processors': (config.get_str_list, 'frame_processors.frame_processors', 'face_swapper'), 
	'ui_layouts': (config.get_str_list, 'uis.ui_layouts', 'default')
	}